# Site settings
title: Jonathan Knott
email: jon@joncknott.com
description: Engineer, Researcher, Entrepreneur.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Jonathan Knott
street_address: 
city: Wollongong
state: NSW
zip_code: 
country: Australia
phone: 

icon: "fa-fire" # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/joncknott/
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/joncknott/
linkedin_url: https://www.linkedin.com/in/joncknott
pinterest_url:
slack_url:
twitter_url: https://twitter.com/joncknott
googlescholar_url: https://scholar.google.com.au/citations?user=CZC38jsAAAAJ&hl=en

# Build settings
markdown: kramdown

sass:
style: compressed

# Google Analytics
google_analytics: G-PJQ9ZGKZXC

# Work Timeline
work:
  - company: "Faculty of Engineering and Information Sciences, University of Wollongong"
    details:
      - date: "October 2022 -"
        position: "Research Fellow"
        description: "Contract research with BlueScope Limited"
      - date: "January 2021 - September 2022"
        position: "Research Fellow"
        description: "DMTC Superconductors project"
  - company: "Institute for Superconducting and Electronic Materials, University of Wollongong"
    details:
      - date: "September 2021 - September 2022"
        position: "Interim Assistant Director"
        description: "Some description"
      - date: "March 2016 - July 2020"
        position: "Project Manager / Research Fellow"
        description: "Different Description"
  - company: "Upward Manufacturing"
    details:
      - date: "September 2021 - September 2022"
        position: "Director"
        description: "Some description"