# Site settings
title: Jonathan Knott
email: jon@joncknott.com
description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Jonathan Knott
street_address: 
city: Wollongong
state: NSW
zip_code: 
country: Australia
phone: 

icon: fa-light fa-fire # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/joncknott/
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/joncknott/
linkedin_url: https://www.linkedin.com/in/joncknott
pinterest_url:
slack_url:
twitter_url: https://twitter.com/joncknott

# Build settings
markdown: kramdown

sass:
style: compressed